# Generated by Django 5.2.3 on 2025-06-22 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('best_month', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treks', to='core.district')),
            ],
        ),
    ]
